import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { chromium } from 'playwright';
import { installHeldWorkers } from '../../../tools/held-worker-harness.mjs';

const source = JSON.parse(readFileSync('fixtures/bbbproj-v5-bind-mesh.json', 'utf8'));
const region = source.artboards[0].nodes[0].skeleton.attachments[0];
region.type = 'region'; region.vertices = region.meshVertices; region.uvs = region.meshUVs;
for (const key of ['meshVertices', 'meshUVs', 'meshTriangles', 'meshHull', 'weights', 'boneBindings']) delete region[key];
const browser = await chromium.launch({ headless: process.env.HEADLESS !== '0' });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } }); page.setDefaultTimeout(30000);
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.addInitScript(installHeldWorkers);
  await page.goto(process.env.SPRINE_URL ?? 'http://localhost:5173/'); await page.waitForFunction(() => window.__ticks > 2);
  const open = async (project) => page.locator('input[type=file]').setInputFiles({ name: 'region.bbbproj', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(project)) });
  const save = async () => { const pending = page.waitForEvent('download'); await page.getByRole('button', { name: 'Save', exact: true }).click(); return JSON.parse(readFileSync(await (await pending).path(), 'utf8')); };
  const select = async () => page.getByText(/^bind test mesh/).first().click();
  const start = async () => { await page.getByRole('button', { name: 'Auto mesh', exact: true }).click(); await page.getByRole('progressbar', { name: 'Auto mesh progress' }).waitFor(); };
  const done = async () => page.waitForFunction(() => window.__workerJobs.at(-1)?.result !== null);
  const columns = page.getByLabel('Auto mesh columns', { exact: true }), rows = page.getByLabel('Auto mesh rows', { exact: true });
  await open(source); await select(); const before = await save();
  await columns.fill('3'); await rows.fill('2'); await start(); await done();
  assert.deepEqual(await save(), before); await page.evaluate(() => window.__releaseWeights());
  await page.locator('footer').getByText(/Auto mesh applied/).waitFor();
  const after = await save(), rig = after.artboards[0].nodes[0], mesh = rig.skeleton.attachments[1];
  assert.deepEqual(rig.skeleton.attachments[0], region); assert.deepEqual(rig.animations, source.artboards[0].nodes[0].animations);
  assert.equal(mesh.type, 'mesh'); assert.equal(mesh.meshVertices.length, 24); assert.equal(mesh.meshTriangles.length, 36);
  assert.equal(rig.skeleton.slots[0].defaultAttachmentId, mesh.id);
  assert.deepEqual(mesh.meshVertices.slice(0, 2), [-50, 80]); assert.deepEqual(mesh.meshVertices.slice(-2), [50, 240]);
  assert.deepEqual(mesh.meshUVs.slice(0, 2), [0, 0]); assert.deepEqual(mesh.meshUVs.slice(-2), [1, 1]);
  await page.keyboard.press('Control+z'); assert.deepEqual(await save(), before);
  await columns.fill('0'); await page.getByRole('button', { name: 'Auto mesh', exact: true }).click();
  await page.locator('footer').getByText(/positive integer subdivisions/).waitFor(); assert.deepEqual(await save(), before);
  await page.keyboard.press('Control+y'); assert.deepEqual(await save(), after);
  await open(after); await select(); assert.deepEqual(await save(), after);
  await open(source); await select(); await columns.fill('99'); await rows.fill('99'); await start(); await done();
  assert.equal(await page.evaluate(() => window.__workerJobs.at(-1).result.result.vertices.length), 20000);
  await page.getByRole('button', { name: 'Cancel auto mesh', exact: true }).click();
  await page.locator('footer').getByText('Auto mesh cancelled.', { exact: true }).waitFor(); assert.deepEqual(await save(), before);
  assert.equal(await page.evaluate(() => window.__workerJobs.at(-1).terminated), true);
  await start(); await done();
  const name = page.getByRole('complementary', { name: 'Character properties' }).getByRole('textbox', { name: 'Name', exact: true });
  await name.fill('changed during mesh job'); await name.press('Enter'); const changed = await save();
  await page.evaluate(() => window.__releaseWeights()); await page.locator('footer').getByText(/Auto mesh discarded because the rig changed/).waitFor();
  assert.deepEqual(await save(), changed);
  await page.keyboard.press('Control+z'); assert.deepEqual(await save(), before);
  await page.keyboard.press('Control+y'); assert.deepEqual(await save(), changed);
  await start(); await page.getByRole('button', { name: 'Animate', exact: true }).click();
  await page.getByRole('progressbar', { name: 'Auto mesh progress' }).waitFor({ state: 'hidden' });
  assert.equal(await page.getByRole('button', { name: 'Auto mesh', exact: true }).isDisabled(), true);
  assert.deepEqual(await save(), changed);
  assert.deepEqual(errors, []);
  console.log('PASS: real auto-mesh worker, 10000-vertex generation, original region/clip preservation, UV corners, exact undo/redo, invalid subdivision redo, native roundtrip, hard cancel, stale and mode isolation');
} finally { await browser.close(); }
