import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { chromium } from 'playwright';

const source = JSON.parse(readFileSync('fixtures/bbbproj-v5-bind-mesh.json', 'utf8'));
const browser = await chromium.launch({ headless: process.env.HEADLESS !== '0' });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  page.setDefaultTimeout(15000);
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(process.env.SPRINE_URL ?? 'http://localhost:5173/');
  await page.waitForFunction(() => window.__ticks > 2);
  const open = async (project) => page.locator('input[type=file]').setInputFiles({ name: 'binding.bbbproj', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(project)) });
  const save = async () => { const pending = page.waitForEvent('download'); await page.getByRole('button', { name: 'Save', exact: true }).click(); return JSON.parse(readFileSync(await (await pending).path(), 'utf8')); };
  const select = async () => page.getByText(/^bind test mesh/).first().click();
  const starting = structuredClone(source), mesh = starting.artboards[0].nodes[0].skeleton.attachments[0];
  delete mesh.weights; delete mesh.boneBindings;
  await open(starting); await select(); const before = await save();
  await page.getByLabel('Mesh binding bones', { exact: true }).selectOption(['tip']);
  await page.getByRole('button', { name: 'Bind setup pose', exact: true }).click();
  const bound = await save();
  assert.deepEqual(bound.artboards[0].nodes[0].skeleton.attachments[0].boneBindings, source.artboards[0].nodes[0].skeleton.attachments[0].boneBindings);
  await page.waitForFunction(() => Math.abs(window.__slotMesh0?.[0] + 50) < 0.01);
  await page.keyboard.press('Control+z'); assert.deepEqual(await save(), before);
  await page.getByLabel('Mesh binding bones', { exact: true }).selectOption([]);
  await page.getByRole('button', { name: 'Bind setup pose', exact: true }).click();
  await page.locator('footer').getByText(/Choose at least one/).waitFor();
  assert.deepEqual(await save(), before);
  await page.keyboard.press('Control+y'); assert.deepEqual(await save(), bound);
  await open(source); await select(); assert.deepEqual(await save(), source);
  await page.getByRole('button', { name: 'Animate', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Bind setup pose', exact: true }).isDisabled(), true);
  await page.locator('.cursor-ew-resize').first().click({ position: { x: 50, y: 12 } });
  await page.waitForFunction(() => Math.abs(window.__slotMesh0?.[0] + 20) < 0.01);
  assert.deepEqual(await save(), source);
  await page.keyboard.press('m');
  const screen = (x, y) => page.evaluate(([x, y]) => window.__worldToScreen(x, y), [x, y]);
  await page.mouse.move(...await screen(-20, 80)); await page.mouse.down();
  await page.mouse.move(...await screen(-35, 65)); await page.mouse.up();
  await page.waitForFunction(() => Math.abs(window.__slotMesh0?.[0] + 35) < 0.1 && Math.abs(window.__slotMesh0?.[1] - 65) < 0.1);
  const deformed = await save(), track = deformed.artboards[0].nodes[0].animations[0].timelines.find((item) => item.kind === 'deform');
  assert.ok(Math.abs(track.keyframes[0].time - 0.5) < 0.001);
  track.keyframes[0].offsets.slice(0, 2).forEach((value) => assert.ok(Math.abs(value + 15) < 0.1));
  await page.keyboard.press('Control+z'); assert.deepEqual(await save(), source);
  await page.keyboard.press('Control+y'); assert.deepEqual(await save(), deformed);
  await page.getByRole('button', { name: 'Setup', exact: true }).click();
  await page.waitForFunction(() => Math.abs(window.__slotMesh0?.[0] + 50) < 0.01);
  const invalid = structuredClone(deformed);
  invalid.artboards[0].nodes[0].skeleton.attachments[0].boneBindings[0].matrix = [0, 0, 0, 0, 0, 0];
  await open(invalid); await page.locator('footer').getByText(/singular transform/).waitFor();
  assert.deepEqual(await save(), deformed);
  assert.deepEqual(errors, []);
  await page.screenshot({ path: 'packages/editor/.smoke/mesh-binding.png' });
  console.log('PASS: native binding, setup shape, atomic rejected selection/import, exact undo/redo, animated pose and weighted cursor/deform alignment');
} finally { await browser.close(); }
