import { CURRENT_SOURCE_SCHEMA } from '../../../tools/project-schema.mjs';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { chromium } from 'playwright';

const source = JSON.parse(readFileSync('fixtures/bbbproj-v6-shared-mesh.json', 'utf8'));
source.schemaVersion = CURRENT_SOURCE_SCHEMA;
const browser = await chromium.launch({ headless: process.env.HEADLESS !== '0' });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1200 } }); page.setDefaultTimeout(20000);
  const errors = []; page.on('pageerror', (error) => errors.push(error.message));
  await page.goto(process.env.SPRINE_URL ?? 'http://localhost:5173/');
  await page.waitForFunction(() => window.__ticks > 2);
  const open = async (project, name = 'shared.bbbproj') => {
    await page.locator('input[type=file]').setInputFiles({ name, mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(project)) });
    await page.locator('footer').getByText(new RegExp(`Opened ${name}|Open failed:`)).waitFor();
  };
  let lastSave = 0;
  const save = async () => {
    await page.waitForTimeout(Math.max(0, 150 - (Date.now() - lastSave)));
    const pending = page.waitForEvent('download'); await page.getByRole('button', { name: 'Save', exact: true }).click();
    const download = await pending; lastSave = Date.now(); return JSON.parse(readFileSync(await download.path(), 'utf8'));
  };
  const rig = (project) => project.artboards[0].nodes[0];
  const select = async (slotName) => page.getByText(new RegExp(`^${slotName}`)).first().click();
  await open(source); await select('variant slot'); assert.deepEqual(await save(), source);
  await page.getByRole('button', { name: 'Create shared mesh', exact: true }).click();
  const created = await save(), instance = rig(created).skeleton.attachments.at(-1);
  assert.equal(instance.meshSourceId, 'mesh'); assert.equal(instance.meshVertices, undefined);
  assert.deepEqual(instance.weights, rig(created).skeleton.attachments[1].weights);
  assert.equal(rig(created).animations[0].timelines.filter((track) => track.kind === 'deform').length, 2);
  await page.keyboard.press('Control+z'); assert.deepEqual(await save(), source);
  await page.keyboard.press('Control+y'); assert.deepEqual(await save(), created);
  await select('bind test mesh'); await page.keyboard.press('m');
  const screen = (x, y) => page.evaluate(([x,y]) => window.__worldToScreen(x,y), [x,y]);
  const drag = async (from, to) => { await page.mouse.move(...await screen(...from)); await page.mouse.down(); await page.mouse.move(...await screen(...to)); await page.mouse.up(); };
  await drag([-50,80], [-55,75]); await page.waitForFunction(() => Math.abs(window.__slotMesh0?.[0] + 55) < 0.1);
  const edited = await save(); assert.ok(Math.abs(rig(edited).skeleton.attachments[0].meshVertices[0] + 55) < 0.1);
  assert.deepEqual(rig(edited).animations, rig(created).animations);
  await page.keyboard.press('Control+z'); assert.deepEqual(await save(), created);
  await page.keyboard.press('Control+y'); assert.deepEqual(await save(), edited);
  await page.getByRole('button', { name: 'Delete mesh', exact: true }).click();
  await page.locator('footer').getByText(/Detach shared meshes before deleting/).waitFor();
  assert.deepEqual(await save(), edited);
  await select('variant slot'); await page.getByRole('button', { name: 'Animate', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Detach shared mesh', exact: true }).isDisabled(), true);
  await page.locator('.cursor-ew-resize').first().click({ position: { x: 50, y: 12 } });
  await drag([-55,85], [-60,90]);
  const animated = await save();
  const tracks = rig(animated).animations[0].timelines.filter((track) => track.kind === 'deform');
  assert.deepEqual(tracks.find((track) => track.attachmentId === 'variant'), rig(source).animations[0].timelines.find((track) => track.kind === 'deform'));
  const key = tracks.find((track) => track.attachmentId === instance.id).keyframes.find((key) => Math.abs(key.time - 0.5) < 0.001);
  assert.ok(key, 'editing the shared instance keys its own Deform');
  assert.ok(Math.abs(key.offsets[0] + 5) < 0.1 && Math.abs(key.offsets[1] - 15) < 0.1);
  await page.keyboard.press('Control+z'); assert.deepEqual(await save(), edited);
  await page.keyboard.press('Control+y'); assert.deepEqual(await save(), animated);
  await page.getByRole('button', { name: 'Setup', exact: true }).click();
  await page.getByRole('button', { name: 'Detach shared mesh', exact: true }).click();
  const detached = await save(), owned = rig(detached).skeleton.attachments.at(-1);
  assert.equal(owned.meshSourceId, undefined); assert.deepEqual(owned.meshVertices, rig(detached).skeleton.attachments[0].meshVertices);
  assert.deepEqual(rig(detached).animations, rig(animated).animations);
  await page.keyboard.press('Control+z'); assert.deepEqual(await save(), animated);
  await page.keyboard.press('Control+y'); assert.deepEqual(await save(), detached);
  await open(detached, 'detached.bbbproj'); assert.deepEqual(await save(), detached);
  await open(animated, 'linked.bbbproj'); assert.deepEqual(await save(), animated);
  const malformed = structuredClone(animated); rig(malformed).skeleton.attachments[1].meshSourceId = 'missing';
  await open(malformed, 'invalid.bbbproj'); await page.locator('footer').getByText(/shared mesh source/).waitFor();
  assert.deepEqual(await save(), animated); assert.deepEqual(errors, []);
  await select('variant slot');
  await page.screenshot({ path: 'packages/editor/.smoke/shared-meshes.png' });
  console.log('PASS: shared geometry creation/editing, independent Deform, detach, source-delete guard, exact history, native roundtrip and invalid-import isolation');
} finally { await browser.close(); }
